name: AutoSell
main: de.xnonymous.autosell.AutoSell
author: XNonymous, SirOswaldo
version: '${project.version}'
website: https://kayteam.org
depend: [Vault]
softdepend: [PlaceholderAPI]
api-version: 1.18
commands:
  BuyAutoSellChest:
    description: Buy one or more Autosell chests
    usage: /buyautosellchest [player] [amount]
  GiveAutoSellChest:
    usage: /giveautosellchest [player] [amount]
    description: Give
  EnableAutoSellChestDebug:
    description: Enable Debug
  ListAutoSellChests:
    description: List Chests
  ReloadAutoSellConfig:
    description: Reload Plugin