name: AutoSell
author: XNonymous
main: de.xnonymous.autosell.AutoSell
version: v1.1
commands:
  GiveAutoSellChest:
    permission: autosell.give
  EnableAutoSellChestDebug:
    permission: autosell.debug
  ListAutoSellChests:
    permission: autosell.list
depend:
  - Essentials
  - Vault