name: AutoSell
author: XNonymous
main: de.xnonymous.autosell.AutoSell
version: v1.2
commands:
  GiveAutoSellChest:
    permission: autosell.give
  EnableAutoSellChestDebug:
    permission: autosell.debug
  ListAutoSellChests:
    permission: autosell.list
  ReloadAutoSellConfig:
    permission: autosell.reload
depend:
  - Vault